### ISSUE TITLE
Suggestion: Update to .NET 4.6.2

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/consoleApp-deltaQuery-dotNet-sample#2]
My main reason: 

https://github.com/microsoftgraph/ConsoleApp-DeltaQuery-DotNet-Sample/blob/master/Client/packages.config#L3

This is a *very, very* old version of ADAL. Tested with 3.14.1, one necessary code change in Client.cs line no 168:

AuthenticationResult authenticationResult = authenticationContext.AcquireToken(this.protectedResourcePrincipalId, clientCred);

to

AuthenticationResult authenticationResult = authenticationContext.AcquireTokenAsync(this.protectedResourcePrincipalId, clientCred).GetAwaiter().GetResult();

**Comment by madhumitadange** [comment]
Updated to MSAL . Thanks :)
